"""empty message

Revision ID: 1541680138f
Revises: None
Create Date: 2015-07-27 21:40:18.471248

"""

# revision identifiers, used by Alembic.
revision = '1541680138f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
