"""empty message

Revision ID: 252b528607f
Revises: 5e571dc761
Create Date: 2015-07-31 17:53:15.143642

"""

# revision identifiers, used by Alembic.
revision = '252b528607f'
down_revision = '5e571dc761'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'created_on',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'created_on',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    ### end Alembic commands ###
