"""empty message

Revision ID: 29636725288
Revises: 104b33f7e28
Create Date: 2015-07-29 17:45:40.463708

"""

# revision identifiers, used by Alembic.
revision = '29636725288'
down_revision = '104b33f7e28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siteusers')
    op.create_table('siteusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siteusers')
    ### end Alembic commands ###
